apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapiv2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapiv2
  template:
    metadata:
      labels:
        app: fastapiv2
    spec:
      containers:
        - name: fastapiv2
          image: guhan286/sparkfastapi:latest
          ports:
            - containerPort: 8000