apiVersion: v1
kind: Service
metadata:
  name: fastapiv2
spec:
  type: NodePort
  selector:
    app: fastapiv2
  ports:
    - name: http
      port: 5000
      targetPort: 8000
      nodePort: 30009
      protocol: TCP
