apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv 
spec:
 capacity:
   storage: 1Gi
 accessModes:
   - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: standard
 hostPath:
   path: "/home/username/kuber"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: pvc
spec:
 accessModes:
   - ReadWriteOnce
 storageClassName: standard
 resources:
   requests:
     storage: 1Gi